import { NextResponse } from "next/server";
import { toggleWorkingEmailActive, resetWorkingEmailPassword } from "@/lib/db/queries";

export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await req.json();

    if (body.action === "RESET_PASSWORD") {
      const result = await resetWorkingEmailPassword(id);
      return NextResponse.json({
        success: true,
        data: result,
        message: "Cryptographic password regenerated by Super Admin",
      });
    }

    if (typeof body.isActive === "boolean") {
      const updated = await toggleWorkingEmailActive(id, body.isActive);
      return NextResponse.json({
        success: true,
        data: updated,
        message: body.isActive ? "Working email activated" : "Working email deactivated",
      });
    }

    return NextResponse.json({ success: false, error: "Invalid action" }, { status: 400 });
  } catch (error: any) {
    return NextResponse.json(
      { success: false, error: error.message || "Failed to update working email" },
      { status: 500 }
    );
  }
}
