import { BusinessCategory, CaseStudy, Lead, MediaAsset, ServiceOffering } from "./types";

export const SAMPLE_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: "media-honey-01",
    title: "Wild Forest Raw Amber Honey",
    url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1200&q=85",
    fileType: "image",
    category: "food-honey",
    clientName: "Vedika Organics",
    campaignHeadline: "PURE GOLD. ZERO COMPROMISE.",
    metrics: {
      views: "1.4M+",
      roas: "6.2x ROAS",
      conversions: "8,400+ Orders",
      leads: "14.2k",
    },
    palette: {
      dominant: "#D97706",
      vibrant: "#F59E0B",
      darkVibrant: "#78350F",
      lightVibrant: "#FEF3C7",
      muted: "#B45309",
      darkMuted: "#451A03",
      contrastText: "#FFFFFF",
      accentFrame: "#F59E0B",
      isDarkImage: true,
      frameAngle: "-2.8deg",
    },
  },
  {
    id: "media-sports-02",
    title: "Veebro HyperSpeed Pro Studs",
    url: "https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=1200&q=85",
    fileType: "image",
    category: "sports-football",
    clientName: "Veebro Athletics",
    campaignHeadline: "SPEED BEYOND MEASURE.",
    metrics: {
      views: "2.8M+",
      roas: "7.8x ROAS",
      conversions: "12,200+ Pairs",
      leads: "28.5k",
    },
    palette: {
      dominant: "#DC2626",
      vibrant: "#EF4444",
      darkVibrant: "#450A0A",
      lightVibrant: "#FEE2E2",
      muted: "#991B1B",
      darkMuted: "#1E0404",
      contrastText: "#FFFFFF",
      accentFrame: "#EF4444",
      isDarkImage: true,
      frameAngle: "3.2deg",
    },
  },
  {
    id: "media-property-03",
    title: "Skyline Panorama Luxury Suites",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
    fileType: "image",
    category: "property",
    clientName: "Altura Living",
    campaignHeadline: "LIVE ABOVE THE ORDINARY.",
    metrics: {
      views: "890k+",
      roas: "14.5x ROAS",
      conversions: "32 Units Sold",
      leads: "420+ HNIs",
    },
    palette: {
      dominant: "#0284C7",
      vibrant: "#0EA5E9",
      darkVibrant: "#0C4A6E",
      lightVibrant: "#E0F2FE",
      muted: "#0369A1",
      darkMuted: "#082F49",
      contrastText: "#FFFFFF",
      accentFrame: "#0EA5E9",
      isDarkImage: true,
      frameAngle: "-1.8deg",
    },
  },
  {
    id: "media-fashion-04",
    title: "Tokyo Midnight Cyber Hoodie",
    url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85",
    fileType: "image",
    category: "fashion-apparel",
    clientName: "Kuro Streetwear",
    campaignHeadline: "UNAPOLOGETIC DRIP.",
    metrics: {
      views: "3.1M+",
      roas: "5.9x ROAS",
      conversions: "15,000+ Units",
      leads: "32k",
    },
    palette: {
      dominant: "#9333EA",
      vibrant: "#A855F7",
      darkVibrant: "#3B0764",
      lightVibrant: "#F3E8FF",
      muted: "#7E22CE",
      darkMuted: "#1E0234",
      contrastText: "#FFFFFF",
      accentFrame: "#A855F7",
      isDarkImage: true,
      frameAngle: "2.4deg",
    },
  },
  {
    id: "media-local-05",
    title: "Artisan Woodfired Crust & Brew",
    url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=85",
    fileType: "image",
    category: "local-shop",
    clientName: "Dough & Oak Pizzeria",
    campaignHeadline: "LOCAL FLAVOR. VIRAL HYPEMACHINE.",
    metrics: {
      views: "640k+",
      roas: "4.8x ROAS",
      conversions: "4,500+ Footfalls",
      leads: "6.2k",
    },
    palette: {
      dominant: "#EA580C",
      vibrant: "#F97316",
      darkVibrant: "#431407",
      lightVibrant: "#FFEDD5",
      muted: "#C2410C",
      darkMuted: "#270B04",
      contrastText: "#FFFFFF",
      accentFrame: "#F97316",
      isDarkImage: true,
      frameAngle: "-3.5deg",
    },
  },
  {
    id: "media-creator-06",
    title: "Arena Live Concert Tour 2026",
    url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=85",
    fileType: "image",
    category: "creator-influencer",
    clientName: "DJ SonicPulse & Viral Plug Events",
    campaignHeadline: "SOLD OUT IN 47 MINUTES.",
    metrics: {
      views: "5.6M+",
      roas: "11.2x ROAS",
      conversions: "28,000 Tickets",
      leads: "64k",
    },
    palette: {
      dominant: "#06B6D4",
      vibrant: "#00F0FF",
      darkVibrant: "#083344",
      lightVibrant: "#CFFAFE",
      muted: "#0891B2",
      darkMuted: "#041B24",
      contrastText: "#FFFFFF",
      accentFrame: "#00F0FF",
      isDarkImage: true,
      frameAngle: "1.9deg",
    },
  },
];

export const SERVICES_DATA: ServiceOffering[] = [
  {
    id: "service-property",
    slug: "property-promotion",
    title: "Property & Real Estate Blitz",
    tagline: "High-ticket room, villa, and residential development lead generation.",
    category: "property",
    badge: "HIGH ROI",
    description: "Cinematic walkthroughs, geo-targeted HNI lead generation, and dynamic comic-poster creative ads that deliver verified site visits and buyer inquiries.",
    keyFeatures: [
      "Drone & architectural 4K visual storytelling",
      "Micro-targeted HNI ads on Meta, YouTube & Google",
      "WhatsApp automated site-visit booking bot",
      "Weekly verified buyer lead pipeline reports",
    ],
    deliverables: ["12 Cinematic Video Creatives", "40 High-Res Ad Posters", "Complete WhatsApp Automation", "Dedicated Media Strategist"],
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85",
    palette: {
      dominant: "#0284C7",
      vibrant: "#0EA5E9",
      darkVibrant: "#0C4A6E",
      lightVibrant: "#E0F2FE",
      muted: "#0369A1",
      darkMuted: "#082F49",
      contrastText: "#FFFFFF",
      accentFrame: "#0EA5E9",
      isDarkImage: true,
      frameAngle: "-2deg",
    },
    startingPrice: "₹45,000 / month",
  },
  {
    id: "service-brands",
    slug: "brand-growth",
    title: "D2C Brand & FMCG Viral Launch",
    tagline: "Explosive e-commerce sales for food, honey, apparel, and lifestyle products.",
    category: "food-honey",
    badge: "MOST POPULAR",
    description: "High-energy comic-poster ad formats and viral UGC creator blitzes engineered to scale ROAS from 2.5x to 7x+ on Shopify and marketplaces.",
    keyFeatures: [
      "Media-Reactive Comic ad creative framework",
      "Influencer seeding with top micro & macro creators",
      "Performance funnel optimization (Meta + TikTok + Google PMax)",
      "High-converting landing page enhancements",
    ],
    deliverables: ["25 Video Variations (Hook Tested)", "60 Graphic Ad Assets", "Creator Seeding Management", "Real-time ROAS Tracker"],
    heroImage: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1000&q=85",
    palette: {
      dominant: "#D97706",
      vibrant: "#F59E0B",
      darkVibrant: "#78350F",
      lightVibrant: "#FEF3C7",
      muted: "#B45309",
      darkMuted: "#451A03",
      contrastText: "#FFFFFF",
      accentFrame: "#F59E0B",
      isDarkImage: true,
      frameAngle: "2.5deg",
    },
    startingPrice: "₹65,000 / month",
  },
  {
    id: "service-sports",
    slug: "sports-apparel",
    title: "Sports & Footwear Domination",
    tagline: "High-intensity athletic campaigns engineered for drops and sports gear.",
    category: "sports-football",
    badge: "VIRAL ENERGY",
    description: "Dynamic action-driven sports creative wrapped in pulse-pounding speed-lines and starburst badges that turn sports enthusiasts into brand evangelists.",
    keyFeatures: [
      "Dynamic athletic motion capture",
      "Pre-launch drop waitlist hype funnels",
      "Athlete & sports creator partnership blitzes",
      "Flash-sale conversion engines",
    ],
    deliverables: ["30 High-Velocity Video Cuts", "50 Drop Poster Variations", "Interactive Countdown Waitlist", "Creator PR Kits"],
    heroImage: "https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=1000&q=85",
    palette: {
      dominant: "#DC2626",
      vibrant: "#EF4444",
      darkVibrant: "#450A0A",
      lightVibrant: "#FEE2E2",
      muted: "#991B1B",
      darkMuted: "#1E0404",
      contrastText: "#FFFFFF",
      accentFrame: "#EF4444",
      isDarkImage: true,
      frameAngle: "-3deg",
    },
    startingPrice: "₹55,000 / month",
  },
  {
    id: "service-local",
    slug: "local-business",
    title: "Local Store & Footfall Engine",
    tagline: "Fill your restaurant, cafe, showroom, or retail store with local footfalls.",
    category: "local-shop",
    badge: "LOCAL LEADER",
    description: "Hyper-local geo-fencing campaigns, local food/lifestyle creator walk-ins, and mouthwatering comic-poster promo flyers that get people through your doors.",
    keyFeatures: [
      "Hyper-local 5km-15km radius ad targeting",
      "Local influencer walk-in tastings & reviews",
      "Google Business Profile 5-star review acceleration",
      "Exclusive WhatsApp loyalty coupon distribution",
    ],
    deliverables: ["8 Local Video Spotlights", "20 Promo Menu / Flyer Creatives", "5 Creator Visit Collaterals", "WhatsApp Footfall Tracker"],
    heroImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=85",
    palette: {
      dominant: "#EA580C",
      vibrant: "#F97316",
      darkVibrant: "#431407",
      lightVibrant: "#FFEDD5",
      muted: "#C2410C",
      darkMuted: "#270B04",
      contrastText: "#FFFFFF",
      accentFrame: "#F97316",
      isDarkImage: true,
      frameAngle: "1.8deg",
    },
    startingPrice: "₹30,000 / month",
  },
];

export const CASE_STUDIES_DATA: CaseStudy[] = [
  {
    id: "cs-01",
    slug: "vedika-raw-honey",
    title: "How Vedika Organics Scaled Raw Forest Honey to ₹48L/Month at 6.2x ROAS",
    clientName: "Vedika Organics",
    category: "food-honey",
    categoryLabel: "FOOD & ORGANIC D2C",
    heroImage: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1200&q=85",
    campaignHeadline: "PURE GOLD. ZERO COMPROMISE.",
    stickerText: "6.2x ROAS 🔥",
    summary: "Transformed an artisanal raw honey brand into a nationwide household name by ditching boring organic stock visuals for high-contrast, mouth-watering honey drip comic posters.",
    results: [
      { metric: "6.2x", value: "ROAS", label: "Blended Return On Ad Spend" },
      { metric: "8,400+", value: "Orders", label: "Monthly Direct Orders" },
      { metric: "₹48.5L", value: "Revenue", label: "Monthly Gross Sales" },
      { metric: "₹185", value: "CAC", label: "Customer Acquisition Cost" },
    ],
    challenge: "Vedika was lost in a sea of generic green organic honey brands with 1.4x ROAS, struggling with high customer acquisition costs and low repeat purchase rates.",
    solution: "We deployed the Media-Reactive Comic Poster framework: macro 4K amber honey pours framed in explosive golden-yellow comic starbursts with bold proof callouts, paired with 20 top food creator reels.",
    palette: {
      dominant: "#D97706",
      vibrant: "#F59E0B",
      darkVibrant: "#78350F",
      lightVibrant: "#FEF3C7",
      muted: "#B45309",
      darkMuted: "#451A03",
      contrastText: "#FFFFFF",
      accentFrame: "#F59E0B",
      isDarkImage: true,
      frameAngle: "-2.8deg",
    },
  },
  {
    id: "cs-02",
    slug: "veebro-hyperspeed",
    title: "Veebro Football Cleat Drop: 12,200 Pairs Sold Out in 14 Days",
    clientName: "Veebro Athletics",
    category: "sports-football",
    categoryLabel: "SPORTS GEAR & DROPS",
    heroImage: "https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=1200&q=85",
    campaignHeadline: "SPEED BEYOND MEASURE.",
    stickerText: "SOLD OUT! ⚡",
    summary: "Built an explosive 3-week hype engine for professional carbon-stud boots across Indian football youth and collegiate leagues.",
    results: [
      { metric: "12,200", value: "Pairs", label: "Units Sold in 14 Days" },
      { metric: "7.8x", value: "ROAS", label: "Ad Spend Efficiency" },
      { metric: "2.8M", value: "Views", label: "Organic + Paid Reach" },
      { metric: "48k+", value: "Waitlist", label: "Pre-Launch Subscribers" },
    ],
    challenge: "Breaking through the dominance of multinational sports giants with a premium ₹6,499 domestic performance cleat.",
    solution: "High-octane red speed-line comic posters capturing split-second boot flex, athlete test benchmarks, and a high-urgency VIP early access waitlist.",
    palette: {
      dominant: "#DC2626",
      vibrant: "#EF4444",
      darkVibrant: "#450A0A",
      lightVibrant: "#FEE2E2",
      muted: "#991B1B",
      darkMuted: "#1E0404",
      contrastText: "#FFFFFF",
      accentFrame: "#EF4444",
      isDarkImage: true,
      frameAngle: "3.2deg",
    },
  },
  {
    id: "cs-03",
    slug: "altura-skyline-living",
    title: "Altura Living: 32 Penthouse Bookings (₹112 Cr Gross Value) in 90 Days",
    clientName: "Altura Living",
    category: "property",
    categoryLabel: "LUXURY REAL ESTATE",
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
    campaignHeadline: "LIVE ABOVE THE ORDINARY.",
    stickerText: "₹112 CR SOLD 🏆",
    summary: "Targeted ultra-high-net-worth individuals with high-definition sunset terrace visuals wrapped in sophisticated sky-blue architectural comic borders.",
    results: [
      { metric: "32", value: "Units Sold", label: "Penthouses & 4BHKs" },
      { metric: "₹112 Cr", value: "Gross Value", label: "Total Booked Inventory" },
      { metric: "420+", value: "HNI Inquiries", label: "Verified Buyer Leads" },
      { metric: "14.5x", value: "ROI", label: "Sales ROI on Ad Budget" },
    ],
    challenge: "High cost-per-lead and poor lead quality from standard real estate portal listings.",
    solution: "Exclusive architectural drone reels and media-reactive sky-blue posters routed directly to a white-glove WhatsApp concierge service.",
    palette: {
      dominant: "#0284C7",
      vibrant: "#0EA5E9",
      darkVibrant: "#0C4A6E",
      lightVibrant: "#E0F2FE",
      muted: "#0369A1",
      darkMuted: "#082F49",
      contrastText: "#FFFFFF",
      accentFrame: "#0EA5E9",
      isDarkImage: true,
      frameAngle: "-1.8deg",
    },
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-101",
    name: "Vikram Malhotra",
    businessName: "Himalayan Nectar Apiaries",
    category: "food-honey",
    phone: "+91 98765 43210",
    email: "vikram@himalayanbeeraw.com",
    budgetRange: "₹50k-₹1.5L / mo",
    timeline: "Immediately (Within 7 days)",
    notes: "Has 3 raw honey variants. Wants viral video ads and Shopify ROAS scaling.",
    leadScore: 92,
    status: "NEW",
    primaryMedia: SAMPLE_MEDIA_ASSETS[0],
    createdAt: "2026-09-02T10:30:00Z",
    updatedAt: "2026-09-02T10:30:00Z",
    assignedTo: "Harshit R. (Lead Strategist)",
  },
  {
    id: "lead-102",
    name: "Aman Preet Singh",
    businessName: "Apex Turf Football Academy",
    category: "sports-football",
    phone: "+91 98111 22334",
    email: "aman@apexturf.in",
    budgetRange: "₹25k-₹50k / mo",
    timeline: "Within 2-3 weeks",
    notes: "Promoting elite weekend training batches and turf bookings in South Delhi.",
    leadScore: 78,
    status: "CONTACTED",
    primaryMedia: SAMPLE_MEDIA_ASSETS[1],
    createdAt: "2026-09-01T15:15:00Z",
    updatedAt: "2026-09-02T09:00:00Z",
    assignedTo: "Rahul Sharma",
  },
  {
    id: "lead-103",
    name: "Sneha Kapadia",
    businessName: "Vistara Haven Residences",
    category: "property",
    phone: "+91 99220 88776",
    email: "sneha@vistarahaven.com",
    budgetRange: "₹1.5L+ / mo",
    timeline: "Immediately",
    notes: "34 luxury sea-facing 3BHK flats in Bandra. High priority campaign.",
    leadScore: 98,
    status: "QUALIFIED",
    primaryMedia: SAMPLE_MEDIA_ASSETS[2],
    createdAt: "2026-08-31T11:45:00Z",
    updatedAt: "2026-09-01T16:20:00Z",
    assignedTo: "Harshit R. (Lead Strategist)",
  },
  {
    id: "lead-104",
    name: "Rohan Varma",
    businessName: "Krafted Crust Pizza Lab",
    category: "local-shop",
    phone: "+91 97654 32109",
    email: "rohan@kraftedcrust.com",
    budgetRange: "₹25k-₹50k / mo",
    timeline: "Next month",
    notes: "Opening 2nd outlet in Indiranagar Bangalore. Wants 500+ launch footfalls.",
    leadScore: 84,
    status: "PROPOSAL_SENT",
    primaryMedia: SAMPLE_MEDIA_ASSETS[4],
    createdAt: "2026-08-30T14:00:00Z",
    updatedAt: "2026-09-02T11:10:00Z",
    assignedTo: "Pooja Roy",
  },
];
